// Generated by gen_imgui_puerts_bindings.py

#include "PuertsXImGui.h"
#include "UnrealImGuiModule.h"
#include "Binding.hpp"
#include "PuertsXImGuiExtend.h"

class UnrealImGui
{
};

UsingCppType(UnrealImGui);
UsingCppType(ImDrawChannel);
UsingCppType(ImDrawCmd);
UsingCppType(ImDrawData);
UsingCppType(ImDrawList);
UsingCppType(ImDrawListSharedData);
UsingCppType(ImDrawListSplitter);
UsingCppType(ImDrawVert);
UsingCppType(ImFont);
UsingCppType(ImFontAtlas);
UsingCppType(ImFontBuilderIO);
UsingCppType(ImFontConfig);
UsingCppType(ImFontGlyph);
UsingCppType(ImFontGlyphRangesBuilder);
UsingCppType(ImColor);
UsingCppType(ImGuiContext);
UsingCppType(ImGuiIO);
UsingCppType(ImGuiInputTextCallbackData);
UsingCppType(ImGuiListClipper);
UsingCppType(ImGuiOnceUponAFrame);
UsingCppType(ImGuiPayload);
// UsingCppType(ImGuiSizeCallbackData);
UsingCppType(ImGuiStorage);
// UsingCppType(ImGuiStyle);
// UsingCppType(ImGuiTableSortSpecs);
// UsingCppType(ImGuiTableColumnSortSpecs);
UsingCppType(ImGuiTextBuffer);
UsingCppType(ImGuiTextFilter);;
UsingCppType(ImGuiViewport)

// DeclOverloads(ImGui_RadioButton);
// DeclOverload(ImGui_RadioButton, bool (*)(const char*, bool), &ImGui::RadioButton);
// DeclOverload(ImGui_RadioButton, bool (*)(const char*, int*, int), &ImGui::RadioButton);

struct AutoRegisterForCPP
{
    AutoRegisterForCPP()
    {
        puerts::DefineClass<UnrealImGui>()
        // Context creation and access
            // .Function("CreateContext", MakeFunction(&ImGui::CreateContext, nullptr))
            // .Function("DestroyContext", MakeFunction(&ImGui::DestroyContext, nullptr))
            // .Function("GetCurrentContext", MakeFunction(&ImGui::GetCurrentContext))
            // .Function("SetCurrentContext", MakeFunction(&ImGui::SetCurrentContext))
        // Main
            // .Function("GetIO", MakeFunction(&ImGui::GetIO))
            // .Function("GetStyle", MakeFunction(&ImGui::GetStyle))
            .Function("NewFrame", MakeFunction(&ImGui::NewFrame))
            .Function("EndFrame", MakeFunction(&ImGui::EndFrame))
            .Function("Render", MakeFunction(&ImGui::Render))
            // .Function("GetDrawData", MakeFunction(&ImGui::GetDrawData))
        // Demo, Debug, Information
            .Function("ShowDemoWindow", MakeFunction(&ImGui::ShowDemoWindow, nullptr))
            .Function("ShowMetricsWindow", MakeFunction(&ImGui::ShowMetricsWindow, nullptr))
            .Function("ShowStackToolWindow", MakeFunction(&ImGui::ShowStackToolWindow, nullptr))
            .Function("ShowAboutWindow", MakeFunction(&ImGui::ShowAboutWindow, nullptr))
            .Function("ShowStyleEditor", MakeFunction(&ImGui::ShowStyleEditor, nullptr))
            .Function("ShowStyleSelector", MakeFunction(&ImGui::ShowStyleSelector))
            .Function("ShowFontSelector", MakeFunction(&ImGui::ShowFontSelector))
            .Function("ShowUserGuide", MakeFunction(&ImGui::ShowUserGuide))
            .Function("GetVersion", MakeFunction(&ImGui::GetVersion))
        // Styles
            .Function("StyleColorsDark", MakeFunction(&ImGui::StyleColorsDark, nullptr))
            .Function("StyleColorsLight", MakeFunction(&ImGui::StyleColorsLight, nullptr))
            .Function("StyleColorsClassic", MakeFunction(&ImGui::StyleColorsClassic, nullptr))
            .Function("Begin", MakeFunction(&ImGui::Begin, nullptr, 0))
            .Function("End", MakeFunction(&ImGui::End))
        // Child Windows
            .Function("BeginChild", SelectFunction(bool (*)(const char*, const ImVec2&, bool, ImGuiWindowFlags), &ImGui::BeginChild, ImVec2(0, 0), false, 0))
            .Function("EndChild", MakeFunction(&ImGui::EndChild))
        // Windows Utilities
            .Function("IsWindowAppearing", MakeFunction(&ImGui::IsWindowAppearing))
            .Function("IsWindowCollapsed", MakeFunction(&ImGui::IsWindowCollapsed))
            .Function("IsWindowFocused", MakeFunction(&ImGui::IsWindowFocused, 0))
            .Function("IsWindowHovered", MakeFunction(&ImGui::IsWindowHovered, 0))
            // .Function("GetWindowDrawList", MakeFunction(&ImGui::GetWindowDrawList))
            .Function("GetWindowPos", MakeFunction(&ImGui::GetWindowPos))
            .Function("GetWindowSize", MakeFunction(&ImGui::GetWindowSize))
            .Function("GetWindowWidth", MakeFunction(&ImGui::GetWindowWidth))
            .Function("GetWindowHeight", MakeFunction(&ImGui::GetWindowHeight))
        // Window manipulation
            .Function("SetNextWindowPos", MakeFunction(&ImGui::SetNextWindowPos, 0, ImVec2(0, 0)))
            .Function("SetNextWindowSize", MakeFunction(&ImGui::SetNextWindowSize, 0))
            // .Function("SetNextWindowSizeConstraints", MakeFunction(&ImGui::SetNextWindowSizeConstraints, nullptr, nullptr))
            .Function("SetNextWindowContentSize", MakeFunction(&ImGui::SetNextWindowContentSize))
            .Function("SetNextWindowCollapsed", MakeFunction(&ImGui::SetNextWindowCollapsed, 0))
            .Function("SetNextWindowFocus", MakeFunction(&ImGui::SetNextWindowFocus))
            .Function("SetNextWindowBgAlpha", MakeFunction(&ImGui::SetNextWindowBgAlpha))
            .Function("SetWindowPos", SelectFunction(void (*)(const char*, const ImVec2&, ImGuiCond), &ImGui::SetWindowPos, 0))
            .Function("SetWindowSize", SelectFunction(void (*)(const char*, const ImVec2&, ImGuiCond), &ImGui::SetWindowSize, 0))
            .Function("SetWindowCollapsed", SelectFunction(void (*)(const char*, bool, ImGuiCond), &ImGui::SetWindowCollapsed, 0))
            .Function("SetWindowFocus", SelectFunction(void (*)(const char*), &ImGui::SetWindowFocus))
        // Content region
            .Function("GetContentRegionAvail", MakeFunction(&ImGui::GetContentRegionAvail))
            .Function("GetContentRegionMax", MakeFunction(&ImGui::GetContentRegionMax))
            .Function("GetWindowContentRegionMin", MakeFunction(&ImGui::GetWindowContentRegionMin))
            .Function("GetWindowContentRegionMax", MakeFunction(&ImGui::GetWindowContentRegionMax))
        // Windows Scrolling
            .Function("GetScrollX", MakeFunction(&ImGui::GetScrollX))
            .Function("GetScrollY", MakeFunction(&ImGui::GetScrollY))
            .Function("SetScrollX", MakeFunction(&ImGui::SetScrollX))
            .Function("SetScrollY", MakeFunction(&ImGui::SetScrollY))
            .Function("GetScrollMaxX", MakeFunction(&ImGui::GetScrollMaxX))
            .Function("GetScrollMaxY", MakeFunction(&ImGui::GetScrollMaxY))
            .Function("SetScrollHereX", MakeFunction(&ImGui::SetScrollHereX, 0.5f))
            .Function("SetScrollHereY", MakeFunction(&ImGui::SetScrollHereY, 0.5f))
            .Function("SetScrollFromPosX", MakeFunction(&ImGui::SetScrollFromPosX, 0.5f))
            .Function("SetScrollFromPosY", MakeFunction(&ImGui::SetScrollFromPosY, 0.5f))
        // Parameters stacks (shared)
            // .Function("PushFont", MakeFunction(&ImGui::PushFont))
            // .Function("PopFont", MakeFunction(&ImGui::PopFont))
        // IMGUI_API void          PushStyleColor(ImGuiCol idx, ImU32 col);
            .Function("PushStyleColor", SelectFunction(void (*)(ImGuiCol, const ImVec4&), &ImGui::PushStyleColor))
            .Function("PopStyleColor", MakeFunction(&ImGui::PopStyleColor, 1))
            .Function("PushStyleVar", SelectFunction(void (*)(ImGuiStyleVar, float), &ImGui::PushStyleVar))
        // IMGUI_API void          PushStyleVar(ImGuiStyleVar idx, const ImVec2& val);
            .Function("PopStyleVar", MakeFunction(&ImGui::PopStyleVar, 1))
            .Function("PushAllowKeyboardFocus", MakeFunction(&ImGui::PushAllowKeyboardFocus))
            .Function("PopAllowKeyboardFocus", MakeFunction(&ImGui::PopAllowKeyboardFocus))
            .Function("PushButtonRepeat", MakeFunction(&ImGui::PushButtonRepeat))
            .Function("PopButtonRepeat", MakeFunction(&ImGui::PopButtonRepeat))
        // Parameters stacks (current window)
            .Function("PushItemWidth", MakeFunction(&ImGui::PushItemWidth))
            .Function("PopItemWidth", MakeFunction(&ImGui::PopItemWidth))
            .Function("SetNextItemWidth", MakeFunction(&ImGui::SetNextItemWidth))
            .Function("CalcItemWidth", MakeFunction(&ImGui::CalcItemWidth))
            .Function("PushTextWrapPos", MakeFunction(&ImGui::PushTextWrapPos, 0.0f))
            .Function("PopTextWrapPos", MakeFunction(&ImGui::PopTextWrapPos))
        // Style read access
            // .Function("GetFont", MakeFunction(&ImGui::GetFont))
            // .Function("GetFontSize", MakeFunction(&ImGui::GetFontSize))
            // .Function("GetFontTexUvWhitePixel", MakeFunction(&ImGui::GetFontTexUvWhitePixel))
            // .Function("GetColorU32", SelectFunction(ImU32 (*)(ImGuiCol, float), &ImGui::GetColorU32, 1.0f))
        // IMGUI_API ImU32         GetColorU32(const ImVec4& col);
        // IMGUI_API ImU32         GetColorU32(ImU32 col);
            // .Function("GetStyleColorVec4", MakeFunction(&ImGui::GetStyleColorVec4))
        // Cursor / Layout
            .Function("Separator", MakeFunction(&ImGui::Separator))
            .Function("SameLine", MakeFunction(&ImGui::SameLine, 0.0f, -1.0f))
            .Function("NewLine", MakeFunction(&ImGui::NewLine))
            .Function("Spacing", MakeFunction(&ImGui::Spacing))
            .Function("Dummy", MakeFunction(&ImGui::Dummy))
            .Function("Indent", MakeFunction(&ImGui::Indent, 0.0f))
            .Function("Unindent", MakeFunction(&ImGui::Unindent, 0.0f))
            .Function("BeginGroup", MakeFunction(&ImGui::BeginGroup))
            .Function("EndGroup", MakeFunction(&ImGui::EndGroup))
            .Function("GetCursorPos", MakeFunction(&ImGui::GetCursorPos))
            .Function("GetCursorPosX", MakeFunction(&ImGui::GetCursorPosX))
            .Function("GetCursorPosY", MakeFunction(&ImGui::GetCursorPosY))
            .Function("SetCursorPos", MakeFunction(&ImGui::SetCursorPos))
            .Function("SetCursorPosX", MakeFunction(&ImGui::SetCursorPosX))
            .Function("SetCursorPosY", MakeFunction(&ImGui::SetCursorPosY))
            .Function("GetCursorStartPos", MakeFunction(&ImGui::GetCursorStartPos))
            .Function("GetCursorScreenPos", MakeFunction(&ImGui::GetCursorScreenPos))
            .Function("SetCursorScreenPos", MakeFunction(&ImGui::SetCursorScreenPos))
            .Function("AlignTextToFramePadding", MakeFunction(&ImGui::AlignTextToFramePadding))
            .Function("GetTextLineHeight", MakeFunction(&ImGui::GetTextLineHeight))
            .Function("GetTextLineHeightWithSpacing", MakeFunction(&ImGui::GetTextLineHeightWithSpacing))
            .Function("GetFrameHeight", MakeFunction(&ImGui::GetFrameHeight))
            .Function("GetFrameHeightWithSpacing", MakeFunction(&ImGui::GetFrameHeightWithSpacing))
        // ID stack/scopes
            .Function("PushID", SelectFunction(void (*)(const char*), &ImGui::PushID))
        // IMGUI_API void          PushID(const char* str_id_begin, const char* str_id_end);
        // IMGUI_API void          PushID(const void* ptr_id);
        // IMGUI_API void          PushID(int int_id);
        // IMGUI_API void          PushID(const void* ptr_id);
            .Function("PopID", MakeFunction(&ImGui::PopID))
            .Function("GetID", SelectFunction(ImGuiID (*)(const char*), &ImGui::GetID))
        // IMGUI_API ImGuiID       GetID(const char* str_id_begin, const char* str_id_end);
        // IMGUI_API ImGuiID       GetID(const void* ptr_id);
        // Widgets: Text
            .Function("TextUnformatted", MakeFunction(&ImGui::TextUnformatted, nullptr))
            .Function("Text", MakeFunction(&PuertsXImGui::Text))
            .Function("TextColored", MakeFunction(&PuertsXImGui::TextColored))
            .Function("TextDisabled", MakeFunction(&PuertsXImGui::TextDisabled))
            .Function("TextWrapped", MakeFunction(&PuertsXImGui::TextWrapped))
            .Function("LabelText", MakeFunction(&PuertsXImGui::LabelText))
            .Function("BulletText", MakeFunction(&PuertsXImGui::BulletText))
        // Widgets: Main
            .Function("Button", MakeFunction(&ImGui::Button, ImVec2(0,0)))
            .Function("SmallButton", MakeFunction(&ImGui::SmallButton))
            .Function("InvisibleButton", MakeFunction(&ImGui::InvisibleButton, 0))
            .Function("ArrowButton", MakeFunction(&ImGui::ArrowButton))
            .Function("Image", MakeFunction(&ImGui::Image, ImVec2(0,0), ImVec2(1,1), ImVec4(1,1,1,1), ImVec4(0,0,0,0)))
            .Function("ImageButton", MakeFunction(&ImGui::ImageButton, ImVec2(0,0), ImVec2(1,1), -1, ImVec4(0,0,0,0), ImVec4(1,1,1,1)))
            .Function("Checkbox", MakeFunction(&ImGui::Checkbox))
            .Function("CheckboxFlags", SelectFunction(bool (*)(const char*, int*, int), &ImGui::CheckboxFlags))
            .Function("RadioButton", SelectFunction(bool (*)(const char*, bool), &ImGui::RadioButton))
            // .Function("RadioButton", CombineOverloads(
            //     SelectOverload(ImGui_RadioButton, bool (*)(const char*, bool))
                // Do not know why cause Error: invalid parameter! yet
                // SelectOverload(ImGui_RadioButton, bool (*)(const char*, int*, int))
            // ))
            .Function("ProgressBar", MakeFunction(&ImGui::ProgressBar, ImVec2(-FLT_MIN,0), nullptr))
            .Function("Bullet", MakeFunction(&ImGui::Bullet))
        // Widgets: Combo Box
            .Function("BeginCombo", MakeFunction(&ImGui::BeginCombo, 0))
            .Function("EndCombo", MakeFunction(&ImGui::EndCombo))
            // .Function("Combo", SelectFunction(bool (*)(const char*, int*, const char* const [], int, int), &ImGui::Combo, -1))
            .Function("Combo", SelectFunction(bool (*)(const char*, int*, const char*, int), &ImGui::Combo, -1))
        // Widgets: Drag Sliders
            .Function("DragFloat", MakeFunction(&ImGui::DragFloat, 1.0f, 0.0f, 0.0f, "%.3f", 0))
            .Function("DragFloat2", MakeFunction(&ImGui::DragFloat2, 1.0f, 0.0f, 0.0f, "%.3f", 0))
            .Function("DragFloat3", MakeFunction(&ImGui::DragFloat3, 1.0f, 0.0f, 0.0f, "%.3f", 0))
            .Function("DragFloat4", MakeFunction(&ImGui::DragFloat4, 1.0f, 0.0f, 0.0f, "%.3f", 0))
            .Function("DragFloatRange2", MakeFunction(&ImGui::DragFloatRange2, 1.0f, 0.0f, 0.0f, "%.3f", nullptr, 0))
            .Function("DragInt", MakeFunction(&ImGui::DragInt, 1.0f, 0, 0, "%d", 0))
            .Function("DragInt2", MakeFunction(&ImGui::DragInt2, 1.0f, 0, 0, "%d", 0))
            .Function("DragInt3", MakeFunction(&ImGui::DragInt3, 1.0f, 0, 0, "%d", 0))
            .Function("DragInt4", MakeFunction(&ImGui::DragInt4, 1.0f, 0, 0, "%d", 0))
            .Function("DragIntRange2", MakeFunction(&ImGui::DragIntRange2, 1.0f, 0, 0, "%d", nullptr, 0))
        // Widgets: Regular Sliders
            .Function("SliderFloat", MakeFunction(&ImGui::SliderFloat, "%.3f", 0))
            .Function("SliderFloat2", MakeFunction(&ImGui::SliderFloat2, "%.3f", 0))
            .Function("SliderFloat3", MakeFunction(&ImGui::SliderFloat3, "%.3f", 0))
            .Function("SliderFloat4", MakeFunction(&ImGui::SliderFloat4, "%.3f", 0))
            .Function("SliderAngle", MakeFunction(&ImGui::SliderAngle, -360.0f, +360.0f, "%.0f deg", 0))
            .Function("SliderInt", MakeFunction(&ImGui::SliderInt, "%d", 0))
            .Function("SliderInt2", MakeFunction(&ImGui::SliderInt2, "%d", 0))
            .Function("SliderInt3", MakeFunction(&ImGui::SliderInt3, "%d", 0))
            .Function("SliderInt4", MakeFunction(&ImGui::SliderInt4, "%d", 0))
            .Function("VSliderFloat", MakeFunction(&ImGui::VSliderFloat, "%.3f", 0))
            .Function("VSliderInt", MakeFunction(&ImGui::VSliderInt, "%d", 0))
        // Widgets: Input with Keyboard
            .Function("InputText", MakeFunction(&PuertsXImGui::InputText, 0))
            .Function("InputTextMultiline", MakeFunction(&PuertsXImGui::InputTextMultiline, ImVec2(0,0), 0))
            .Function("InputTextWithHint", MakeFunction(&PuertsXImGui::InputTextWithHint, 0))
            .Function("InputFloat", MakeFunction(&ImGui::InputFloat, 0.0f, 0.0f, "%.3f", 0))
            .Function("InputFloat2", MakeFunction(&ImGui::InputFloat2, "%.3f", 0))
            .Function("InputFloat3", MakeFunction(&ImGui::InputFloat3, "%.3f", 0))
            .Function("InputFloat4", MakeFunction(&ImGui::InputFloat4, "%.3f", 0))
            .Function("InputInt", MakeFunction(&ImGui::InputInt, 1, 100, 0))
            .Function("InputInt2", MakeFunction(&ImGui::InputInt2, 0))
            .Function("InputInt3", MakeFunction(&ImGui::InputInt3, 0))
            .Function("InputInt4", MakeFunction(&ImGui::InputInt4, 0))
            .Function("InputDouble", MakeFunction(&ImGui::InputDouble, 0.0, 0.0, "%.6f", 0))
        // Widgets: Color Editor/Picker (tip: the ColorEdit* functions have a little color square that can be left-clicked to open a picker, and right-clicked to open an option menu.)
            .Function("ColorEdit3", MakeFunction(&ImGui::ColorEdit3, 0))
            .Function("ColorEdit4", MakeFunction(&ImGui::ColorEdit4, 0))
            .Function("ColorPicker3", MakeFunction(&ImGui::ColorPicker3, 0))
            .Function("ColorPicker4", MakeFunction(&ImGui::ColorPicker4, 0, nullptr))
            .Function("ColorButton", MakeFunction(&ImGui::ColorButton, 0, ImVec2(0,0)))
            .Function("SetColorEditOptions", MakeFunction(&ImGui::SetColorEditOptions))
        // Widgets: Trees
            .Function("TreeNode", MakeFunction(&PuertsXImGui::TreeNode))
            .Function("TreeNodeEx", MakeFunction(&PuertsXImGui::TreeNodeEx))
            .Function("TreePush", SelectFunction(void (*)(const char*), &ImGui::TreePush))
            .Function("TreePop", MakeFunction(&ImGui::TreePop))
            .Function("GetTreeNodeToLabelSpacing", MakeFunction(&ImGui::GetTreeNodeToLabelSpacing))
            .Function("CollapsingHeader", SelectFunction(bool (*)(const char*, bool*, ImGuiTreeNodeFlags), &ImGui::CollapsingHeader, 0))
            .Function("SetNextItemOpen", MakeFunction(&ImGui::SetNextItemOpen, 0))
        // Widgets: Selectables
            .Function("Selectable", SelectFunction(bool (*)(const char*, bool*, ImGuiSelectableFlags, const ImVec2&), &ImGui::Selectable, 0, ImVec2(0,0)))
        // Widgets: List Boxes
            .Function("BeginListBox", MakeFunction(&ImGui::BeginListBox, ImVec2(0,0)))
            .Function("EndListBox", MakeFunction(&ImGui::EndListBox))
            // .Function("ListBox", MakeFunction(&ImGui::ListBox, -1))
        // Widgets: Data Plotting
            // .Function("PlotLines", MakeFunction(&ImGui::PlotLines, 0, nullptr, FLT_MAX, FLT_MAX, ImVec2(0,0), sizeof(float)))
            // .Function("PlotHistogram", MakeFunction(&ImGui::PlotHistogram, 0, nullptr, FLT_MAX, FLT_MAX, ImVec2(0,0), sizeof(float)))
        // Widgets: Value() Helpers.
            // .Function("Value", MakeFunction(&ImGui::Value))
            // .Function("Value", MakeFunction(&ImGui::Value))
            // .Function("Value", MakeFunction(&ImGui::Value))
            // .Function("Value", MakeFunction(&ImGui::Value, nullptr))
        // Widgets: Menus
            .Function("BeginMenuBar", MakeFunction(&ImGui::BeginMenuBar))
            .Function("EndMenuBar", MakeFunction(&ImGui::EndMenuBar))
            .Function("BeginMainMenuBar", MakeFunction(&ImGui::BeginMainMenuBar))
            .Function("EndMainMenuBar", MakeFunction(&ImGui::EndMainMenuBar))
            .Function("BeginMenu", MakeFunction(&ImGui::BeginMenu, true))
            .Function("EndMenu", MakeFunction(&ImGui::EndMenu))
            .Function("MenuItem", SelectFunction(bool (*)(const char*, const char*, bool*, bool), &ImGui::MenuItem, false))
        // Tooltips
            .Function("BeginTooltip", MakeFunction(&ImGui::BeginTooltip))
            .Function("EndTooltip", MakeFunction(&ImGui::EndTooltip))
            .Function("SetTooltip", MakeFunction(&PuertsXImGui::SetTooltip))
        // Popups: begin/end functions
            .Function("BeginPopup", MakeFunction(&ImGui::BeginPopup, 0))
            .Function("BeginPopupModal", MakeFunction(&ImGui::BeginPopupModal, nullptr, 0))
            .Function("EndPopup", MakeFunction(&ImGui::EndPopup))
        // Popups: open/close functions
            .Function("OpenPopup", SelectFunction(void (*)(const char*, ImGuiPopupFlags), &ImGui::OpenPopup, 0))
            .Function("OpenPopupOnItemClick", MakeFunction(&ImGui::OpenPopupOnItemClick, nullptr, 1))
            .Function("CloseCurrentPopup", MakeFunction(&ImGui::CloseCurrentPopup))
        // Popups: open+begin combined functions helpers
            .Function("BeginPopupContextItem", MakeFunction(&ImGui::BeginPopupContextItem, nullptr, 1))
            .Function("BeginPopupContextWindow", MakeFunction(&ImGui::BeginPopupContextWindow, nullptr, 1))
            .Function("BeginPopupContextVoid", MakeFunction(&ImGui::BeginPopupContextVoid, nullptr, 1))
        // Popups: query functions
            .Function("IsPopupOpen", MakeFunction(&ImGui::IsPopupOpen, 0))
        // Tables
            .Function("BeginTable", MakeFunction(&ImGui::BeginTable, 0, ImVec2(0.0f,0.0f), 0.0f))
            .Function("EndTable", MakeFunction(&ImGui::EndTable))
            .Function("TableNextRow", MakeFunction(&ImGui::TableNextRow, 0, 0.0f))
            .Function("TableNextColumn", MakeFunction(&ImGui::TableNextColumn))
            .Function("TableSetColumnIndex", MakeFunction(&ImGui::TableSetColumnIndex))
        // Tables: Headers & Columns declaration
            .Function("TableSetupColumn", MakeFunction(&ImGui::TableSetupColumn, 0, 0.0f, 0))
            .Function("TableSetupScrollFreeze", MakeFunction(&ImGui::TableSetupScrollFreeze))
            .Function("TableHeadersRow", MakeFunction(&ImGui::TableHeadersRow))
            .Function("TableHeader", MakeFunction(&ImGui::TableHeader))
            // .Function("TableGetSortSpecs", MakeFunction(&ImGui::TableGetSortSpecs))
        // Tables: Miscellaneous functions
            .Function("TableGetColumnCount", MakeFunction(&ImGui::TableGetColumnCount))
            .Function("TableGetColumnIndex", MakeFunction(&ImGui::TableGetColumnIndex))
            .Function("TableGetRowIndex", MakeFunction(&ImGui::TableGetRowIndex))
            .Function("TableGetColumnName", MakeFunction(&ImGui::TableGetColumnName, -1))
            .Function("TableGetColumnFlags", MakeFunction(&ImGui::TableGetColumnFlags, -1))
            .Function("TableSetColumnEnabled", MakeFunction(&ImGui::TableSetColumnEnabled))
            .Function("TableSetBgColor", MakeFunction(&ImGui::TableSetBgColor, -1))
        // Legacy Columns API (prefer using Tables!)
            // .Function("Columns", MakeFunction(&ImGui::Columns, 1, nullptr, true))
            // .Function("NextColumn", MakeFunction(&ImGui::NextColumn))
            // .Function("GetColumnIndex", MakeFunction(&ImGui::GetColumnIndex))
            // .Function("GetColumnWidth", MakeFunction(&ImGui::GetColumnWidth, -1))
            // .Function("SetColumnWidth", MakeFunction(&ImGui::SetColumnWidth))
            // .Function("GetColumnOffset", MakeFunction(&ImGui::GetColumnOffset, -1))
            // .Function("SetColumnOffset", MakeFunction(&ImGui::SetColumnOffset))
            // .Function("GetColumnsCount", MakeFunction(&ImGui::GetColumnsCount))
        // Tab Bars, Tabs
            .Function("BeginTabBar", MakeFunction(&ImGui::BeginTabBar, 0))
            .Function("EndTabBar", MakeFunction(&ImGui::EndTabBar))
            .Function("BeginTabItem", MakeFunction(&ImGui::BeginTabItem, nullptr, 0))
            .Function("EndTabItem", MakeFunction(&ImGui::EndTabItem))
            .Function("TabItemButton", MakeFunction(&ImGui::TabItemButton, 0))
            .Function("SetTabItemClosed", MakeFunction(&ImGui::SetTabItemClosed))
        // Logging/Capture
            .Function("LogToTTY", MakeFunction(&ImGui::LogToTTY, -1))
            .Function("LogToFile", MakeFunction(&ImGui::LogToFile, -1, nullptr))
            .Function("LogToClipboard", MakeFunction(&ImGui::LogToClipboard, -1))
            .Function("LogFinish", MakeFunction(&ImGui::LogFinish))
            .Function("LogButtons", MakeFunction(&ImGui::LogButtons))
            // .Function("LogText", MakeFunction(&ImGui::LogText))
            .Function("LogTextV", MakeFunction(&ImGui::LogTextV))
        // Drag and Drop
            .Function("BeginDragDropSource", MakeFunction(&ImGui::BeginDragDropSource, 0))
            .Function("EndDragDropSource", MakeFunction(&ImGui::EndDragDropSource))
            .Function("BeginDragDropTarget", MakeFunction(&ImGui::BeginDragDropTarget))
            // .Function("AcceptDragDropPayload", MakeFunction(&ImGui::AcceptDragDropPayload, 0))
            // .Function("EndDragDropTarget", MakeFunction(&ImGui::EndDragDropTarget))
            // .Function("GetDragDropPayload", MakeFunction(&ImGui::GetDragDropPayload))
        // Disabling [BETA API]
            .Function("BeginDisabled", MakeFunction(&ImGui::BeginDisabled, true))
            .Function("EndDisabled", MakeFunction(&ImGui::EndDisabled))
        // Clipping
            .Function("PushClipRect", MakeFunction(&ImGui::PushClipRect))
            .Function("PopClipRect", MakeFunction(&ImGui::PopClipRect))
        // Focus, Activation
            .Function("SetItemDefaultFocus", MakeFunction(&ImGui::SetItemDefaultFocus))
            .Function("SetKeyboardFocusHere", MakeFunction(&ImGui::SetKeyboardFocusHere, 0))
        // Item/Widgets Utilities and Query Functions
            .Function("IsItemHovered", MakeFunction(&ImGui::IsItemHovered, 0))
            .Function("IsItemActive", MakeFunction(&ImGui::IsItemActive))
            .Function("IsItemFocused", MakeFunction(&ImGui::IsItemFocused))
            .Function("IsItemClicked", MakeFunction(&ImGui::IsItemClicked, 0))
            .Function("IsItemVisible", MakeFunction(&ImGui::IsItemVisible))
            .Function("IsItemEdited", MakeFunction(&ImGui::IsItemEdited))
            .Function("IsItemActivated", MakeFunction(&ImGui::IsItemActivated))
            .Function("IsItemDeactivated", MakeFunction(&ImGui::IsItemDeactivated))
            .Function("IsItemDeactivatedAfterEdit", MakeFunction(&ImGui::IsItemDeactivatedAfterEdit))
            .Function("IsItemToggledOpen", MakeFunction(&ImGui::IsItemToggledOpen))
            .Function("IsAnyItemHovered", MakeFunction(&ImGui::IsAnyItemHovered))
            .Function("IsAnyItemActive", MakeFunction(&ImGui::IsAnyItemActive))
            .Function("IsAnyItemFocused", MakeFunction(&ImGui::IsAnyItemFocused))
            .Function("GetItemRectMin", MakeFunction(&ImGui::GetItemRectMin))
            .Function("GetItemRectMax", MakeFunction(&ImGui::GetItemRectMax))
            .Function("GetItemRectSize", MakeFunction(&ImGui::GetItemRectSize))
            .Function("SetItemAllowOverlap", MakeFunction(&ImGui::SetItemAllowOverlap))
        // Viewports
            // .Function("GetMainViewport", MakeFunction(&ImGui::GetMainViewport))
        // Miscellaneous Utilities
            // .Function("IsRectVisible", MakeFunction(&ImGui::IsRectVisible))
            // .Function("IsRectVisible", MakeFunction(&ImGui::IsRectVisible))
            .Function("GetTime", MakeFunction(&ImGui::GetTime))
            .Function("GetFrameCount", MakeFunction(&ImGui::GetFrameCount))
            // .Function("GetBackgroundDrawList", MakeFunction(&ImGui::GetBackgroundDrawList))
            // .Function("GetForegroundDrawList", MakeFunction(&ImGui::GetForegroundDrawList))
            // .Function("GetDrawListSharedData", MakeFunction(&ImGui::GetDrawListSharedData))
            .Function("GetStyleColorName", MakeFunction(&ImGui::GetStyleColorName))
            // .Function("SetStateStorage", MakeFunction(&ImGui::SetStateStorage))
            // .Function("GetStateStorage", MakeFunction(&ImGui::GetStateStorage))
            .Function("CalcListClipping", MakeFunction(&ImGui::CalcListClipping))
            .Function("BeginChildFrame", MakeFunction(&ImGui::BeginChildFrame, 0))
            .Function("EndChildFrame", MakeFunction(&ImGui::EndChildFrame))
        // Text Utilities
            .Function("CalcTextSize", MakeFunction(&ImGui::CalcTextSize, nullptr, false, -1.0f))
        // Color Utilities
            .Function("ColorConvertU32ToFloat4", MakeFunction(&ImGui::ColorConvertU32ToFloat4))
            .Function("ColorConvertFloat4ToU32", MakeFunction(&ImGui::ColorConvertFloat4ToU32))
            .Function("ColorConvertRGBtoHSV", MakeFunction(&ImGui::ColorConvertRGBtoHSV))
            .Function("ColorConvertHSVtoRGB", MakeFunction(&ImGui::ColorConvertHSVtoRGB))
        // Inputs Utilities: Keyboard
            .Function("GetKeyIndex", MakeFunction(&ImGui::GetKeyIndex))
            .Function("IsKeyDown", MakeFunction(&ImGui::IsKeyDown))
            .Function("IsKeyPressed", MakeFunction(&ImGui::IsKeyPressed, true))
            .Function("IsKeyReleased", MakeFunction(&ImGui::IsKeyReleased))
            .Function("GetKeyPressedAmount", MakeFunction(&ImGui::GetKeyPressedAmount))
            .Function("CaptureKeyboardFromApp", MakeFunction(&ImGui::CaptureKeyboardFromApp, true))
        // Inputs Utilities: Mouse
            .Function("IsMouseDown", MakeFunction(&ImGui::IsMouseDown))
            .Function("IsMouseClicked", MakeFunction(&ImGui::IsMouseClicked, false))
            .Function("IsMouseReleased", MakeFunction(&ImGui::IsMouseReleased))
            .Function("IsMouseDoubleClicked", MakeFunction(&ImGui::IsMouseDoubleClicked))
            .Function("IsMouseHoveringRect", MakeFunction(&ImGui::IsMouseHoveringRect, true))
            .Function("IsMousePosValid", MakeFunction(&ImGui::IsMousePosValid, nullptr))
            .Function("IsAnyMouseDown", MakeFunction(&ImGui::IsAnyMouseDown))
            .Function("GetMousePos", MakeFunction(&ImGui::GetMousePos))
            .Function("GetMousePosOnOpeningCurrentPopup", MakeFunction(&ImGui::GetMousePosOnOpeningCurrentPopup))
            .Function("IsMouseDragging", MakeFunction(&ImGui::IsMouseDragging, -1.0f))
            .Function("GetMouseDragDelta", MakeFunction(&ImGui::GetMouseDragDelta, 0, -1.0f))
            .Function("ResetMouseDragDelta", MakeFunction(&ImGui::ResetMouseDragDelta, 0))
            .Function("GetMouseCursor", MakeFunction(&ImGui::GetMouseCursor))
            .Function("SetMouseCursor", MakeFunction(&ImGui::SetMouseCursor))
            .Function("CaptureMouseFromApp", MakeFunction(&ImGui::CaptureMouseFromApp, true))
        // Clipboard Utilities
            .Function("GetClipboardText", MakeFunction(&ImGui::GetClipboardText))
            .Function("SetClipboardText", MakeFunction(&ImGui::SetClipboardText))
        // Settings/.Ini Utilities
            .Function("LoadIniSettingsFromDisk", MakeFunction(&ImGui::LoadIniSettingsFromDisk))
            .Function("LoadIniSettingsFromMemory", MakeFunction(&ImGui::LoadIniSettingsFromMemory, 0))
            .Function("SaveIniSettingsToDisk", MakeFunction(&ImGui::SaveIniSettingsToDisk))
            .Function("SaveIniSettingsToMemory", MakeFunction(&ImGui::SaveIniSettingsToMemory, nullptr))
        // Debug Utilities
            .Function("DebugCheckVersionAndDataLayout", MakeFunction(&ImGui::DebugCheckVersionAndDataLayout))
        // Memory Allocators
            // .Function("SetAllocatorFunctions", MakeFunction(&ImGui::SetAllocatorFunctions, nullptr))
            // .Function("GetAllocatorFunctions", MakeFunction(&ImGui::GetAllocatorFunctions))
            // .Function("MemAlloc", MakeFunction(&ImGui::MemAlloc))
            // .Function("MemFree", MakeFunction(&ImGui::MemFree))
            .Register();
    }
};

AutoRegisterForCPP _AutoRegisterForCPP__;